server:
  port: 8083

spring:
  profiles:
    active: production

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/duka
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQLUSER}
    password: ${MYSQL_ROOT_PASSWORD}
    url: jdbc:${MYSQL_PRIVATE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
